spring:
  application:
    name: transformers
    version: 0.1.0
    show: true
  output:
    ansi:
      enabled: DETECT
  aop:
    auto: true
    proxy-target-class: true
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    encoding:
      charset: UTF-8
      force: true
      enabled: true
logging:
  appname: transformers
  config: ./config/logback.xml
filePath: ./config/config.json
checkLoginFilePath: ./config/config.json
allPersonPath: ./config/allPerson.json
miaoshaTime: 16:03:00:010
productId: 4826100
priceList: "[180]"
theaterId: ""
cookies: "Hm_lvt_0cb4627679a11906d6bf0ced685dc014=1667744089; aliyungf_tc=b60935e9cb32ab7a3c924e449f6ffca301fddc56ff8f9052cfdf80022dc23d2e; acw_tc=2f6fc11e16685883755191430eca1aec9b7582809f166bcaece28f324697fa; Hm_lpvt_0cb4627679a11906d6bf0ced685dc014=1668588592"
totalMod: 3
server:
  port: 9093